name: prober4

on: [push]

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: forge
        working-directory: contracts
        run: forge --version
