name: prober6

on: [push]

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup --version stable
          echo "$HOME/.foundry/bin" >> "$GITHUB_PATH"
      - run: forge --version
